### ISSUE TITLE
Unhandled rejection TypeError: Cannot read property 'modified' of undefined     at Router.<anonymous> 

### ISSUE THREAD

**Issue by ajdfajdfl2003** [hexojs/hexo-livereload#7]
#### Exception

> Unhandled rejection TypeError: Cannot read property 'modified' of undefined
>     at Router.<anonymous> (/../hexo/node_modules/hexo-livereload/lib/server.js:24:16)
>     at emitOne (events.js:78:13)
>     at Router.emit (events.js:170:7)
>     at Router.set (/../hexo/node_modules/hexo/lib/hexo/router.js:95:8)
>     at /../hexo/node_modules/hexo/lib/hexo/index.js:344:20
>     at tryCatcher (/../hexo/node_modules/bluebird/js/main/util.js:26:23)
>     at ReductionPromiseArray._promiseFulfilled (/../hexo/node_modules/bluebird/js/main/reduce.js:105:38)
>     at ReductionPromiseArray.init (/../hexo/node_modules/bluebird/js/main/promise_array.js:92:18)
>     at Promise._settlePromiseAt (/../hexo/node_modules/bluebird/js/main/promise.js:579:21)
>     at Promise._settlePromises (/../hexo/node_modules/bluebird/js/main/promise.js:697:14)
>     at Async._drainQueue (/../hexo/node_modules/bluebird/js/main/async.js:123:16)
>     at Async._drainQueues (/../hexo/node_modules/bluebird/js/main/async.js:133:10)
>     at Immediate.Async.drainQueues [as _onImmediate](/../hexo/node_modules/bluebird/js/main/async.js:15:14)
>     at processImmediate [as _immediateCallback](timers.js:384:17)
#### Question
-  it seems hexo 3.1.1 has been remove the function hexo.router.on ?? 
  Cause in hexo-livereload:server.js:24, there is a function called `hexo.router.on`, in /lib/hexo/router.js, there isn't.
  But instead,  a function called `hexo.router.set` is there.
#### Solution
- After I modified server.js:24, hexo.router.on changed to hexo.router.set, there is no more exception showing up. But hexo-livereload still not working.

**Comment by jimmed** [comment]
+1 I'm getting this exact same error

**Comment by goldenlove** [comment]
+ 1 ... same error  -.-|||

**Comment by KevinOfNeu** [comment]
same error

**Comment by ajdfajdfl2003** [comment]
@KevinOfNeu  @goldenlove  Try to follow my solution, I think it will work for you

**Comment by icaroperseo** [comment]
Look at this: https://github.com/hexojs/hexo-browsersync

It's works like a charm!

**Comment by maciejmyslinski** [comment]
same error

**Comment by ManfredHu** [comment]
same error!!

**Comment by Johnzinvalid** [comment]
the hexo-browsersync works for me

**Comment by kuncevich** [comment]
same thing here with the latest hexo 3.2

**Comment by guyunxiang32** [comment]
same error!

**Comment by allenGKC** [comment]
don't need hexo-liveload, just npm install hexo-browsersync --save is OK

**Comment by NoahDragon** [comment]
As mentioned above, use the hexo-browsersync instead.
